#!/bin/sh
# Mongo C Driver uninstall program, generated with CMake
# Copyright 2018-present MongoDB, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

save_pwd=$(pwd)
cd /usr/local/

printf "Removing file \"lib/libbson-static-1.0.a\""
(rm -f "lib/libbson-static-1.0.a" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"lib/cmake/bson-1.0/bson_static-targets.cmake\""
(rm -f "lib/cmake/bson-1.0/bson_static-targets.cmake" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"lib/cmake/bson-1.0/bson_static-targets-release.cmake\""
(rm -f "lib/cmake/bson-1.0/bson_static-targets-release.cmake" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"lib/pkgconfig/libbson-static-1.0.pc\""
(rm -f "lib/pkgconfig/libbson-static-1.0.pc" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"lib/libbson-1.0.so.0.0.0\""
(rm -f "lib/libbson-1.0.so.0.0.0" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"lib/libbson-1.0.so.0\""
(rm -f "lib/libbson-1.0.so.0" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"lib/libbson-1.0.so\""
(rm -f "lib/libbson-1.0.so" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"lib/cmake/bson-1.0/bson_shared-targets.cmake\""
(rm -f "lib/cmake/bson-1.0/bson_shared-targets.cmake" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"lib/cmake/bson-1.0/bson_shared-targets-release.cmake\""
(rm -f "lib/cmake/bson-1.0/bson_shared-targets-release.cmake" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"lib/pkgconfig/libbson-1.0.pc\""
(rm -f "lib/pkgconfig/libbson-1.0.pc" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/libbson-1.0/bson/bson-string.h\""
(rm -f "include/libbson-1.0/bson/bson-string.h" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/libbson-1.0/bson/bson-types.h\""
(rm -f "include/libbson-1.0/bson/bson-types.h" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/libbson-1.0/bson/bson-atomic.h\""
(rm -f "include/libbson-1.0/bson/bson-atomic.h" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/libbson-1.0/bson/bson-context.h\""
(rm -f "include/libbson-1.0/bson/bson-context.h" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/libbson-1.0/bson/bson-error.h\""
(rm -f "include/libbson-1.0/bson/bson-error.h" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/libbson-1.0/bson/bson-utf8.h\""
(rm -f "include/libbson-1.0/bson/bson-utf8.h" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/libbson-1.0/bson/bson-reader.h\""
(rm -f "include/libbson-1.0/bson/bson-reader.h" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/libbson-1.0/bson/bson-json.h\""
(rm -f "include/libbson-1.0/bson/bson-json.h" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/libbson-1.0/bson/bson-keys.h\""
(rm -f "include/libbson-1.0/bson/bson-keys.h" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/libbson-1.0/bson/bson-prelude.h\""
(rm -f "include/libbson-1.0/bson/bson-prelude.h" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/libbson-1.0/bson/bson-macros.h\""
(rm -f "include/libbson-1.0/bson/bson-macros.h" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/libbson-1.0/bson/bson-endian.h\""
(rm -f "include/libbson-1.0/bson/bson-endian.h" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/libbson-1.0/bson/bson-version-functions.h\""
(rm -f "include/libbson-1.0/bson/bson-version-functions.h" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/libbson-1.0/bson/bson-iter.h\""
(rm -f "include/libbson-1.0/bson/bson-iter.h" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/libbson-1.0/bson/bson-writer.h\""
(rm -f "include/libbson-1.0/bson/bson-writer.h" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/libbson-1.0/bson/bson-cmp.h\""
(rm -f "include/libbson-1.0/bson/bson-cmp.h" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/libbson-1.0/bson/bson-oid.h\""
(rm -f "include/libbson-1.0/bson/bson-oid.h" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/libbson-1.0/bson/bson-memory.h\""
(rm -f "include/libbson-1.0/bson/bson-memory.h" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/libbson-1.0/bson/bson-decimal128.h\""
(rm -f "include/libbson-1.0/bson/bson-decimal128.h" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/libbson-1.0/bson/bcon.h\""
(rm -f "include/libbson-1.0/bson/bcon.h" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/libbson-1.0/bson/bson-clock.h\""
(rm -f "include/libbson-1.0/bson/bson-clock.h" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/libbson-1.0/bson/bson-md5.h\""
(rm -f "include/libbson-1.0/bson/bson-md5.h" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/libbson-1.0/bson/bson.h\""
(rm -f "include/libbson-1.0/bson/bson.h" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/libbson-1.0/bson/bson-compat.h\""
(rm -f "include/libbson-1.0/bson/bson-compat.h" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/libbson-1.0/bson/bson-value.h\""
(rm -f "include/libbson-1.0/bson/bson-value.h" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/libbson-1.0/bson/bson-config.h\""
(rm -f "include/libbson-1.0/bson/bson-config.h" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/libbson-1.0/bson/bson-version.h\""
(rm -f "include/libbson-1.0/bson/bson-version.h" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/libbson-1.0/bson.h\""
(rm -f "include/libbson-1.0/bson.h" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"lib/cmake/bson-1.0/bson-1.0-config.cmake\""
(rm -f "lib/cmake/bson-1.0/bson-1.0-config.cmake" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"lib/cmake/bson-1.0/bson-1.0-config-version.cmake\""
(rm -f "lib/cmake/bson-1.0/bson-1.0-config-version.cmake" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"lib/cmake/bson-1.0/bson-targets.cmake\""
(rm -f "lib/cmake/bson-1.0/bson-targets.cmake" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"lib/cmake/libbson-1.0/libbson-1.0-config.cmake\""
(rm -f "lib/cmake/libbson-1.0/libbson-1.0-config.cmake" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"lib/cmake/libbson-1.0/libbson-1.0-config-version.cmake\""
(rm -f "lib/cmake/libbson-1.0/libbson-1.0-config-version.cmake" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"lib/cmake/libbson-static-1.0/libbson-static-1.0-config.cmake\""
(rm -f "lib/cmake/libbson-static-1.0/libbson-static-1.0-config.cmake" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"lib/cmake/libbson-static-1.0/libbson-static-1.0-config-version.cmake\""
(rm -f "lib/cmake/libbson-static-1.0/libbson-static-1.0-config-version.cmake" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"lib/pkgconfig/libmongoc-1.0.pc\""
(rm -f "lib/pkgconfig/libmongoc-1.0.pc" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"lib/pkgconfig/libmongoc-static-1.0.pc\""
(rm -f "lib/pkgconfig/libmongoc-static-1.0.pc" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"bin/mongoc-stat\""
(rm -f "bin/mongoc-stat" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"lib/libmongoc-1.0.so.0.0.0\""
(rm -f "lib/libmongoc-1.0.so.0.0.0" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"lib/libmongoc-1.0.so.0\""
(rm -f "lib/libmongoc-1.0.so.0" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"lib/libmongoc-1.0.so\""
(rm -f "lib/libmongoc-1.0.so" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"lib/libmongoc-static-1.0.a\""
(rm -f "lib/libmongoc-static-1.0.a" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/libmongoc-1.0/mongoc/mongoc-config.h\""
(rm -f "include/libmongoc-1.0/mongoc/mongoc-config.h" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/libmongoc-1.0/mongoc/mongoc-version.h\""
(rm -f "include/libmongoc-1.0/mongoc/mongoc-version.h" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/libmongoc-1.0/mongoc/mongoc.h\""
(rm -f "include/libmongoc-1.0/mongoc/mongoc.h" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/libmongoc-1.0/mongoc/mongoc-apm.h\""
(rm -f "include/libmongoc-1.0/mongoc/mongoc-apm.h" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/libmongoc-1.0/mongoc/mongoc-bulk-operation.h\""
(rm -f "include/libmongoc-1.0/mongoc/mongoc-bulk-operation.h" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/libmongoc-1.0/mongoc/mongoc-change-stream.h\""
(rm -f "include/libmongoc-1.0/mongoc/mongoc-change-stream.h" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/libmongoc-1.0/mongoc/mongoc-client.h\""
(rm -f "include/libmongoc-1.0/mongoc/mongoc-client.h" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/libmongoc-1.0/mongoc/mongoc-client-pool.h\""
(rm -f "include/libmongoc-1.0/mongoc/mongoc-client-pool.h" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/libmongoc-1.0/mongoc/mongoc-client-side-encryption.h\""
(rm -f "include/libmongoc-1.0/mongoc/mongoc-client-side-encryption.h" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/libmongoc-1.0/mongoc/mongoc-collection.h\""
(rm -f "include/libmongoc-1.0/mongoc/mongoc-collection.h" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/libmongoc-1.0/mongoc/mongoc-cursor.h\""
(rm -f "include/libmongoc-1.0/mongoc/mongoc-cursor.h" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/libmongoc-1.0/mongoc/mongoc-database.h\""
(rm -f "include/libmongoc-1.0/mongoc/mongoc-database.h" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/libmongoc-1.0/mongoc/mongoc-error.h\""
(rm -f "include/libmongoc-1.0/mongoc/mongoc-error.h" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/libmongoc-1.0/mongoc/mongoc-flags.h\""
(rm -f "include/libmongoc-1.0/mongoc/mongoc-flags.h" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/libmongoc-1.0/mongoc/mongoc-find-and-modify.h\""
(rm -f "include/libmongoc-1.0/mongoc/mongoc-find-and-modify.h" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/libmongoc-1.0/mongoc/mongoc-gridfs.h\""
(rm -f "include/libmongoc-1.0/mongoc/mongoc-gridfs.h" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/libmongoc-1.0/mongoc/mongoc-gridfs-bucket.h\""
(rm -f "include/libmongoc-1.0/mongoc/mongoc-gridfs-bucket.h" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/libmongoc-1.0/mongoc/mongoc-gridfs-file.h\""
(rm -f "include/libmongoc-1.0/mongoc/mongoc-gridfs-file.h" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/libmongoc-1.0/mongoc/mongoc-gridfs-file-page.h\""
(rm -f "include/libmongoc-1.0/mongoc/mongoc-gridfs-file-page.h" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/libmongoc-1.0/mongoc/mongoc-gridfs-file-list.h\""
(rm -f "include/libmongoc-1.0/mongoc/mongoc-gridfs-file-list.h" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/libmongoc-1.0/mongoc/mongoc-handshake.h\""
(rm -f "include/libmongoc-1.0/mongoc/mongoc-handshake.h" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/libmongoc-1.0/mongoc/mongoc-host-list.h\""
(rm -f "include/libmongoc-1.0/mongoc/mongoc-host-list.h" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/libmongoc-1.0/mongoc/mongoc-init.h\""
(rm -f "include/libmongoc-1.0/mongoc/mongoc-init.h" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/libmongoc-1.0/mongoc/mongoc-index.h\""
(rm -f "include/libmongoc-1.0/mongoc/mongoc-index.h" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/libmongoc-1.0/mongoc/mongoc-iovec.h\""
(rm -f "include/libmongoc-1.0/mongoc/mongoc-iovec.h" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/libmongoc-1.0/mongoc/mongoc-log.h\""
(rm -f "include/libmongoc-1.0/mongoc/mongoc-log.h" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/libmongoc-1.0/mongoc/mongoc-macros.h\""
(rm -f "include/libmongoc-1.0/mongoc/mongoc-macros.h" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/libmongoc-1.0/mongoc/mongoc-matcher.h\""
(rm -f "include/libmongoc-1.0/mongoc/mongoc-matcher.h" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/libmongoc-1.0/mongoc/mongoc-opcode.h\""
(rm -f "include/libmongoc-1.0/mongoc/mongoc-opcode.h" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/libmongoc-1.0/mongoc/mongoc-optional.h\""
(rm -f "include/libmongoc-1.0/mongoc/mongoc-optional.h" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/libmongoc-1.0/mongoc/mongoc-prelude.h\""
(rm -f "include/libmongoc-1.0/mongoc/mongoc-prelude.h" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/libmongoc-1.0/mongoc/mongoc-read-concern.h\""
(rm -f "include/libmongoc-1.0/mongoc/mongoc-read-concern.h" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/libmongoc-1.0/mongoc/mongoc-read-prefs.h\""
(rm -f "include/libmongoc-1.0/mongoc/mongoc-read-prefs.h" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/libmongoc-1.0/mongoc/mongoc-server-api.h\""
(rm -f "include/libmongoc-1.0/mongoc/mongoc-server-api.h" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/libmongoc-1.0/mongoc/mongoc-server-description.h\""
(rm -f "include/libmongoc-1.0/mongoc/mongoc-server-description.h" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/libmongoc-1.0/mongoc/mongoc-client-session.h\""
(rm -f "include/libmongoc-1.0/mongoc/mongoc-client-session.h" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/libmongoc-1.0/mongoc/mongoc-socket.h\""
(rm -f "include/libmongoc-1.0/mongoc/mongoc-socket.h" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/libmongoc-1.0/mongoc/mongoc-stream-tls-libressl.h\""
(rm -f "include/libmongoc-1.0/mongoc/mongoc-stream-tls-libressl.h" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/libmongoc-1.0/mongoc/mongoc-stream-tls-openssl.h\""
(rm -f "include/libmongoc-1.0/mongoc/mongoc-stream-tls-openssl.h" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/libmongoc-1.0/mongoc/mongoc-stream.h\""
(rm -f "include/libmongoc-1.0/mongoc/mongoc-stream.h" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/libmongoc-1.0/mongoc/mongoc-stream-buffered.h\""
(rm -f "include/libmongoc-1.0/mongoc/mongoc-stream-buffered.h" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/libmongoc-1.0/mongoc/mongoc-stream-file.h\""
(rm -f "include/libmongoc-1.0/mongoc/mongoc-stream-file.h" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/libmongoc-1.0/mongoc/mongoc-stream-gridfs.h\""
(rm -f "include/libmongoc-1.0/mongoc/mongoc-stream-gridfs.h" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/libmongoc-1.0/mongoc/mongoc-stream-socket.h\""
(rm -f "include/libmongoc-1.0/mongoc/mongoc-stream-socket.h" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/libmongoc-1.0/mongoc/mongoc-topology-description.h\""
(rm -f "include/libmongoc-1.0/mongoc/mongoc-topology-description.h" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/libmongoc-1.0/mongoc/mongoc-uri.h\""
(rm -f "include/libmongoc-1.0/mongoc/mongoc-uri.h" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/libmongoc-1.0/mongoc/mongoc-version-functions.h\""
(rm -f "include/libmongoc-1.0/mongoc/mongoc-version-functions.h" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/libmongoc-1.0/mongoc/mongoc-write-concern.h\""
(rm -f "include/libmongoc-1.0/mongoc/mongoc-write-concern.h" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/libmongoc-1.0/mongoc/mongoc-rand.h\""
(rm -f "include/libmongoc-1.0/mongoc/mongoc-rand.h" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/libmongoc-1.0/mongoc/mongoc-stream-tls.h\""
(rm -f "include/libmongoc-1.0/mongoc/mongoc-stream-tls.h" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/libmongoc-1.0/mongoc/mongoc-ssl.h\""
(rm -f "include/libmongoc-1.0/mongoc/mongoc-ssl.h" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/libmongoc-1.0/mongoc.h\""
(rm -f "include/libmongoc-1.0/mongoc.h" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"lib/pkgconfig/libmongoc-ssl-1.0.pc\""
(rm -f "lib/pkgconfig/libmongoc-ssl-1.0.pc" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"lib/cmake/mongoc-1.0/mongoc-targets.cmake\""
(rm -f "lib/cmake/mongoc-1.0/mongoc-targets.cmake" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"lib/cmake/mongoc-1.0/mongoc-targets-release.cmake\""
(rm -f "lib/cmake/mongoc-1.0/mongoc-targets-release.cmake" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"lib/cmake/mongoc-1.0/mongoc-1.0-config.cmake\""
(rm -f "lib/cmake/mongoc-1.0/mongoc-1.0-config.cmake" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"lib/cmake/mongoc-1.0/mongoc-1.0-config-version.cmake\""
(rm -f "lib/cmake/mongoc-1.0/mongoc-1.0-config-version.cmake" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"lib/cmake/libmongoc-1.0/libmongoc-1.0-config.cmake\""
(rm -f "lib/cmake/libmongoc-1.0/libmongoc-1.0-config.cmake" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"lib/cmake/libmongoc-1.0/libmongoc-1.0-config-version.cmake\""
(rm -f "lib/cmake/libmongoc-1.0/libmongoc-1.0-config-version.cmake" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"lib/cmake/libmongoc-static-1.0/libmongoc-static-1.0-config.cmake\""
(rm -f "lib/cmake/libmongoc-static-1.0/libmongoc-static-1.0-config.cmake" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"lib/cmake/libmongoc-static-1.0/libmongoc-static-1.0-config-version.cmake\""
(rm -f "lib/cmake/libmongoc-static-1.0/libmongoc-static-1.0-config-version.cmake" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"share/mongo-c-driver/COPYING\""
(rm -f "share/mongo-c-driver/COPYING" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"share/mongo-c-driver/NEWS\""
(rm -f "share/mongo-c-driver/NEWS" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"share/mongo-c-driver/README.rst\""
(rm -f "share/mongo-c-driver/README.rst" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"share/mongo-c-driver/THIRD_PARTY_NOTICES\""
(rm -f "share/mongo-c-driver/THIRD_PARTY_NOTICES" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"share/mongo-c-driver/uninstall.sh\""
(rm -f "share/mongo-c-driver/uninstall.sh" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/bsoncxx/v_noabi/bsoncxx/types.hpp\""
(rm -f "include/bsoncxx/v_noabi/bsoncxx/types.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/bsoncxx/v_noabi/bsoncxx/json-fwd.hpp\""
(rm -f "include/bsoncxx/v_noabi/bsoncxx/json-fwd.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/bsoncxx/v_noabi/bsoncxx/builder/core.hpp\""
(rm -f "include/bsoncxx/v_noabi/bsoncxx/builder/core.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/bsoncxx/v_noabi/bsoncxx/builder/list.hpp\""
(rm -f "include/bsoncxx/v_noabi/bsoncxx/builder/list.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/bsoncxx/v_noabi/bsoncxx/builder/concatenate.hpp\""
(rm -f "include/bsoncxx/v_noabi/bsoncxx/builder/concatenate.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/bsoncxx/v_noabi/bsoncxx/builder/stream/array_context-fwd.hpp\""
(rm -f "include/bsoncxx/v_noabi/bsoncxx/builder/stream/array_context-fwd.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/bsoncxx/v_noabi/bsoncxx/builder/stream/key_context-fwd.hpp\""
(rm -f "include/bsoncxx/v_noabi/bsoncxx/builder/stream/key_context-fwd.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/bsoncxx/v_noabi/bsoncxx/builder/stream/closed_context-fwd.hpp\""
(rm -f "include/bsoncxx/v_noabi/bsoncxx/builder/stream/closed_context-fwd.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/bsoncxx/v_noabi/bsoncxx/builder/stream/array.hpp\""
(rm -f "include/bsoncxx/v_noabi/bsoncxx/builder/stream/array.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/bsoncxx/v_noabi/bsoncxx/builder/stream/document-fwd.hpp\""
(rm -f "include/bsoncxx/v_noabi/bsoncxx/builder/stream/document-fwd.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/bsoncxx/v_noabi/bsoncxx/builder/stream/array_context.hpp\""
(rm -f "include/bsoncxx/v_noabi/bsoncxx/builder/stream/array_context.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/bsoncxx/v_noabi/bsoncxx/builder/stream/value_context.hpp\""
(rm -f "include/bsoncxx/v_noabi/bsoncxx/builder/stream/value_context.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/bsoncxx/v_noabi/bsoncxx/builder/stream/key_context.hpp\""
(rm -f "include/bsoncxx/v_noabi/bsoncxx/builder/stream/key_context.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/bsoncxx/v_noabi/bsoncxx/builder/stream/closed_context.hpp\""
(rm -f "include/bsoncxx/v_noabi/bsoncxx/builder/stream/closed_context.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/bsoncxx/v_noabi/bsoncxx/builder/stream/value_context-fwd.hpp\""
(rm -f "include/bsoncxx/v_noabi/bsoncxx/builder/stream/value_context-fwd.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/bsoncxx/v_noabi/bsoncxx/builder/stream/single_context.hpp\""
(rm -f "include/bsoncxx/v_noabi/bsoncxx/builder/stream/single_context.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/bsoncxx/v_noabi/bsoncxx/builder/stream/helpers.hpp\""
(rm -f "include/bsoncxx/v_noabi/bsoncxx/builder/stream/helpers.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/bsoncxx/v_noabi/bsoncxx/builder/stream/helpers-fwd.hpp\""
(rm -f "include/bsoncxx/v_noabi/bsoncxx/builder/stream/helpers-fwd.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/bsoncxx/v_noabi/bsoncxx/builder/stream/document.hpp\""
(rm -f "include/bsoncxx/v_noabi/bsoncxx/builder/stream/document.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/bsoncxx/v_noabi/bsoncxx/builder/stream/array-fwd.hpp\""
(rm -f "include/bsoncxx/v_noabi/bsoncxx/builder/stream/array-fwd.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/bsoncxx/v_noabi/bsoncxx/builder/stream/single_context-fwd.hpp\""
(rm -f "include/bsoncxx/v_noabi/bsoncxx/builder/stream/single_context-fwd.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/bsoncxx/v_noabi/bsoncxx/builder/list-fwd.hpp\""
(rm -f "include/bsoncxx/v_noabi/bsoncxx/builder/list-fwd.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/bsoncxx/v_noabi/bsoncxx/builder/concatenate-fwd.hpp\""
(rm -f "include/bsoncxx/v_noabi/bsoncxx/builder/concatenate-fwd.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/bsoncxx/v_noabi/bsoncxx/builder/basic/impl.hpp\""
(rm -f "include/bsoncxx/v_noabi/bsoncxx/builder/basic/impl.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/bsoncxx/v_noabi/bsoncxx/builder/basic/array.hpp\""
(rm -f "include/bsoncxx/v_noabi/bsoncxx/builder/basic/array.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/bsoncxx/v_noabi/bsoncxx/builder/basic/kvp.hpp\""
(rm -f "include/bsoncxx/v_noabi/bsoncxx/builder/basic/kvp.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/bsoncxx/v_noabi/bsoncxx/builder/basic/document-fwd.hpp\""
(rm -f "include/bsoncxx/v_noabi/bsoncxx/builder/basic/document-fwd.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/bsoncxx/v_noabi/bsoncxx/builder/basic/sub_document-fwd.hpp\""
(rm -f "include/bsoncxx/v_noabi/bsoncxx/builder/basic/sub_document-fwd.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/bsoncxx/v_noabi/bsoncxx/builder/basic/sub_array.hpp\""
(rm -f "include/bsoncxx/v_noabi/bsoncxx/builder/basic/sub_array.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/bsoncxx/v_noabi/bsoncxx/builder/basic/sub_document.hpp\""
(rm -f "include/bsoncxx/v_noabi/bsoncxx/builder/basic/sub_document.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/bsoncxx/v_noabi/bsoncxx/builder/basic/sub_array-fwd.hpp\""
(rm -f "include/bsoncxx/v_noabi/bsoncxx/builder/basic/sub_array-fwd.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/bsoncxx/v_noabi/bsoncxx/builder/basic/helpers.hpp\""
(rm -f "include/bsoncxx/v_noabi/bsoncxx/builder/basic/helpers.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/bsoncxx/v_noabi/bsoncxx/builder/basic/document.hpp\""
(rm -f "include/bsoncxx/v_noabi/bsoncxx/builder/basic/document.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/bsoncxx/v_noabi/bsoncxx/builder/basic/array-fwd.hpp\""
(rm -f "include/bsoncxx/v_noabi/bsoncxx/builder/basic/array-fwd.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/bsoncxx/v_noabi/bsoncxx/builder/core-fwd.hpp\""
(rm -f "include/bsoncxx/v_noabi/bsoncxx/builder/core-fwd.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/bsoncxx/v_noabi/bsoncxx/view_or_value-fwd.hpp\""
(rm -f "include/bsoncxx/v_noabi/bsoncxx/view_or_value-fwd.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/bsoncxx/v_noabi/bsoncxx/validate-fwd.hpp\""
(rm -f "include/bsoncxx/v_noabi/bsoncxx/validate-fwd.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/bsoncxx/v_noabi/bsoncxx/stdx/type_traits.hpp\""
(rm -f "include/bsoncxx/v_noabi/bsoncxx/stdx/type_traits.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/bsoncxx/v_noabi/bsoncxx/stdx/string_view.hpp\""
(rm -f "include/bsoncxx/v_noabi/bsoncxx/stdx/string_view.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/bsoncxx/v_noabi/bsoncxx/stdx/operators.hpp\""
(rm -f "include/bsoncxx/v_noabi/bsoncxx/stdx/operators.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/bsoncxx/v_noabi/bsoncxx/stdx/optional.hpp\""
(rm -f "include/bsoncxx/v_noabi/bsoncxx/stdx/optional.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/bsoncxx/v_noabi/bsoncxx/stdx/make_unique.hpp\""
(rm -f "include/bsoncxx/v_noabi/bsoncxx/stdx/make_unique.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/bsoncxx/v_noabi/bsoncxx/types/value.hpp\""
(rm -f "include/bsoncxx/v_noabi/bsoncxx/types/value.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/bsoncxx/v_noabi/bsoncxx/types/bson_value/make_value.hpp\""
(rm -f "include/bsoncxx/v_noabi/bsoncxx/types/bson_value/make_value.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/bsoncxx/v_noabi/bsoncxx/types/bson_value/value.hpp\""
(rm -f "include/bsoncxx/v_noabi/bsoncxx/types/bson_value/value.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/bsoncxx/v_noabi/bsoncxx/types/bson_value/view.hpp\""
(rm -f "include/bsoncxx/v_noabi/bsoncxx/types/bson_value/view.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/bsoncxx/v_noabi/bsoncxx/types/bson_value/view-fwd.hpp\""
(rm -f "include/bsoncxx/v_noabi/bsoncxx/types/bson_value/view-fwd.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/bsoncxx/v_noabi/bsoncxx/types/bson_value/value-fwd.hpp\""
(rm -f "include/bsoncxx/v_noabi/bsoncxx/types/bson_value/value-fwd.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/bsoncxx/v_noabi/bsoncxx/types/bson_value/view_or_value.hpp\""
(rm -f "include/bsoncxx/v_noabi/bsoncxx/types/bson_value/view_or_value.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/bsoncxx/v_noabi/bsoncxx/oid-fwd.hpp\""
(rm -f "include/bsoncxx/v_noabi/bsoncxx/oid-fwd.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/bsoncxx/v_noabi/bsoncxx/exception/exception-fwd.hpp\""
(rm -f "include/bsoncxx/v_noabi/bsoncxx/exception/exception-fwd.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/bsoncxx/v_noabi/bsoncxx/exception/exception.hpp\""
(rm -f "include/bsoncxx/v_noabi/bsoncxx/exception/exception.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/bsoncxx/v_noabi/bsoncxx/exception/error_code.hpp\""
(rm -f "include/bsoncxx/v_noabi/bsoncxx/exception/error_code.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/bsoncxx/v_noabi/bsoncxx/exception/error_code-fwd.hpp\""
(rm -f "include/bsoncxx/v_noabi/bsoncxx/exception/error_code-fwd.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/bsoncxx/v_noabi/bsoncxx/json.hpp\""
(rm -f "include/bsoncxx/v_noabi/bsoncxx/json.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/bsoncxx/v_noabi/bsoncxx/string/view_or_value-fwd.hpp\""
(rm -f "include/bsoncxx/v_noabi/bsoncxx/string/view_or_value-fwd.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/bsoncxx/v_noabi/bsoncxx/string/to_string.hpp\""
(rm -f "include/bsoncxx/v_noabi/bsoncxx/string/to_string.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/bsoncxx/v_noabi/bsoncxx/string/view_or_value.hpp\""
(rm -f "include/bsoncxx/v_noabi/bsoncxx/string/view_or_value.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/bsoncxx/v_noabi/bsoncxx/config/prelude.hpp\""
(rm -f "include/bsoncxx/v_noabi/bsoncxx/config/prelude.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/bsoncxx/v_noabi/bsoncxx/config/postlude.hpp\""
(rm -f "include/bsoncxx/v_noabi/bsoncxx/config/postlude.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/bsoncxx/v_noabi/bsoncxx/config/util.hpp\""
(rm -f "include/bsoncxx/v_noabi/bsoncxx/config/util.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/bsoncxx/v_noabi/bsoncxx/config/compiler.hpp\""
(rm -f "include/bsoncxx/v_noabi/bsoncxx/config/compiler.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/bsoncxx/v_noabi/bsoncxx/validate.hpp\""
(rm -f "include/bsoncxx/v_noabi/bsoncxx/validate.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/bsoncxx/v_noabi/bsoncxx/types-fwd.hpp\""
(rm -f "include/bsoncxx/v_noabi/bsoncxx/types-fwd.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/bsoncxx/v_noabi/bsoncxx/array/value.hpp\""
(rm -f "include/bsoncxx/v_noabi/bsoncxx/array/value.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/bsoncxx/v_noabi/bsoncxx/array/view.hpp\""
(rm -f "include/bsoncxx/v_noabi/bsoncxx/array/view.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/bsoncxx/v_noabi/bsoncxx/array/view-fwd.hpp\""
(rm -f "include/bsoncxx/v_noabi/bsoncxx/array/view-fwd.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/bsoncxx/v_noabi/bsoncxx/array/element-fwd.hpp\""
(rm -f "include/bsoncxx/v_noabi/bsoncxx/array/element-fwd.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/bsoncxx/v_noabi/bsoncxx/array/value-fwd.hpp\""
(rm -f "include/bsoncxx/v_noabi/bsoncxx/array/value-fwd.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/bsoncxx/v_noabi/bsoncxx/array/element.hpp\""
(rm -f "include/bsoncxx/v_noabi/bsoncxx/array/element.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/bsoncxx/v_noabi/bsoncxx/array/view_or_value.hpp\""
(rm -f "include/bsoncxx/v_noabi/bsoncxx/array/view_or_value.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/bsoncxx/v_noabi/bsoncxx/decimal128.hpp\""
(rm -f "include/bsoncxx/v_noabi/bsoncxx/decimal128.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/bsoncxx/v_noabi/bsoncxx/oid.hpp\""
(rm -f "include/bsoncxx/v_noabi/bsoncxx/oid.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/bsoncxx/v_noabi/bsoncxx/util/functor.hpp\""
(rm -f "include/bsoncxx/v_noabi/bsoncxx/util/functor.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/bsoncxx/v_noabi/bsoncxx/decimal128-fwd.hpp\""
(rm -f "include/bsoncxx/v_noabi/bsoncxx/decimal128-fwd.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/bsoncxx/v_noabi/bsoncxx/view_or_value.hpp\""
(rm -f "include/bsoncxx/v_noabi/bsoncxx/view_or_value.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/bsoncxx/v_noabi/bsoncxx/enums/binary_sub_type.hpp\""
(rm -f "include/bsoncxx/v_noabi/bsoncxx/enums/binary_sub_type.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/bsoncxx/v_noabi/bsoncxx/enums/type.hpp\""
(rm -f "include/bsoncxx/v_noabi/bsoncxx/enums/type.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/bsoncxx/v_noabi/bsoncxx/document/value.hpp\""
(rm -f "include/bsoncxx/v_noabi/bsoncxx/document/value.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/bsoncxx/v_noabi/bsoncxx/document/view.hpp\""
(rm -f "include/bsoncxx/v_noabi/bsoncxx/document/view.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/bsoncxx/v_noabi/bsoncxx/document/view-fwd.hpp\""
(rm -f "include/bsoncxx/v_noabi/bsoncxx/document/view-fwd.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/bsoncxx/v_noabi/bsoncxx/document/element-fwd.hpp\""
(rm -f "include/bsoncxx/v_noabi/bsoncxx/document/element-fwd.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/bsoncxx/v_noabi/bsoncxx/document/value-fwd.hpp\""
(rm -f "include/bsoncxx/v_noabi/bsoncxx/document/value-fwd.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/bsoncxx/v_noabi/bsoncxx/document/element.hpp\""
(rm -f "include/bsoncxx/v_noabi/bsoncxx/document/element.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/bsoncxx/v_noabi/bsoncxx/document/view_or_value.hpp\""
(rm -f "include/bsoncxx/v_noabi/bsoncxx/document/view_or_value.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/bsoncxx/v_noabi/bsoncxx/config/config.hpp\""
(rm -f "include/bsoncxx/v_noabi/bsoncxx/config/config.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/bsoncxx/v_noabi/bsoncxx/config/version.hpp\""
(rm -f "include/bsoncxx/v_noabi/bsoncxx/config/version.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/bsoncxx/v_noabi/bsoncxx/third_party/mnmlstc/core/utility.hpp\""
(rm -f "include/bsoncxx/v_noabi/bsoncxx/third_party/mnmlstc/core/utility.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/bsoncxx/v_noabi/bsoncxx/third_party/mnmlstc/core/iterator.hpp\""
(rm -f "include/bsoncxx/v_noabi/bsoncxx/third_party/mnmlstc/core/iterator.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/bsoncxx/v_noabi/bsoncxx/third_party/mnmlstc/core/variant.hpp\""
(rm -f "include/bsoncxx/v_noabi/bsoncxx/third_party/mnmlstc/core/variant.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/bsoncxx/v_noabi/bsoncxx/third_party/mnmlstc/core/memory.hpp\""
(rm -f "include/bsoncxx/v_noabi/bsoncxx/third_party/mnmlstc/core/memory.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/bsoncxx/v_noabi/bsoncxx/third_party/mnmlstc/core/type_traits.hpp\""
(rm -f "include/bsoncxx/v_noabi/bsoncxx/third_party/mnmlstc/core/type_traits.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/bsoncxx/v_noabi/bsoncxx/third_party/mnmlstc/core/numeric.hpp\""
(rm -f "include/bsoncxx/v_noabi/bsoncxx/third_party/mnmlstc/core/numeric.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/bsoncxx/v_noabi/bsoncxx/third_party/mnmlstc/core/any.hpp\""
(rm -f "include/bsoncxx/v_noabi/bsoncxx/third_party/mnmlstc/core/any.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/bsoncxx/v_noabi/bsoncxx/third_party/mnmlstc/core/functional.hpp\""
(rm -f "include/bsoncxx/v_noabi/bsoncxx/third_party/mnmlstc/core/functional.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/bsoncxx/v_noabi/bsoncxx/third_party/mnmlstc/core/range.hpp\""
(rm -f "include/bsoncxx/v_noabi/bsoncxx/third_party/mnmlstc/core/range.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/bsoncxx/v_noabi/bsoncxx/third_party/mnmlstc/core/algorithm.hpp\""
(rm -f "include/bsoncxx/v_noabi/bsoncxx/third_party/mnmlstc/core/algorithm.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/bsoncxx/v_noabi/bsoncxx/third_party/mnmlstc/core/string.hpp\""
(rm -f "include/bsoncxx/v_noabi/bsoncxx/third_party/mnmlstc/core/string.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/bsoncxx/v_noabi/bsoncxx/third_party/mnmlstc/core/optional.hpp\""
(rm -f "include/bsoncxx/v_noabi/bsoncxx/third_party/mnmlstc/core/optional.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/bsoncxx/v_noabi/bsoncxx/config/export.hpp\""
(rm -f "include/bsoncxx/v_noabi/bsoncxx/config/export.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"lib/libbsoncxx.so.3.10.1\""
(rm -f "lib/libbsoncxx.so.3.10.1" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"lib/libbsoncxx.so._noabi\""
(rm -f "lib/libbsoncxx.so._noabi" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"lib/libbsoncxx.so\""
(rm -f "lib/libbsoncxx.so" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"lib/cmake/bsoncxx-3.10.1/bsoncxx_targets.cmake\""
(rm -f "lib/cmake/bsoncxx-3.10.1/bsoncxx_targets.cmake" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"lib/cmake/bsoncxx-3.10.1/bsoncxx_targets-release.cmake\""
(rm -f "lib/cmake/bsoncxx-3.10.1/bsoncxx_targets-release.cmake" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"lib/cmake/bsoncxx-3.10.1/bsoncxx-config-version.cmake\""
(rm -f "lib/cmake/bsoncxx-3.10.1/bsoncxx-config-version.cmake" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"lib/cmake/bsoncxx-3.10.1/bsoncxx-config.cmake\""
(rm -f "lib/cmake/bsoncxx-3.10.1/bsoncxx-config.cmake" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"lib/pkgconfig/libbsoncxx.pc\""
(rm -f "lib/pkgconfig/libbsoncxx.pc" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/mongocxx/v_noabi/mongocxx/stdx.hpp\""
(rm -f "include/mongocxx/v_noabi/mongocxx/stdx.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/mongocxx/v_noabi/mongocxx/cursor.hpp\""
(rm -f "include/mongocxx/v_noabi/mongocxx/cursor.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/mongocxx/v_noabi/mongocxx/write_type.hpp\""
(rm -f "include/mongocxx/v_noabi/mongocxx/write_type.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/mongocxx/v_noabi/mongocxx/result/rewrap_many_datakey-fwd.hpp\""
(rm -f "include/mongocxx/v_noabi/mongocxx/result/rewrap_many_datakey-fwd.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/mongocxx/v_noabi/mongocxx/result/replace_one.hpp\""
(rm -f "include/mongocxx/v_noabi/mongocxx/result/replace_one.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/mongocxx/v_noabi/mongocxx/result/insert_many.hpp\""
(rm -f "include/mongocxx/v_noabi/mongocxx/result/insert_many.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/mongocxx/v_noabi/mongocxx/result/bulk_write-fwd.hpp\""
(rm -f "include/mongocxx/v_noabi/mongocxx/result/bulk_write-fwd.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/mongocxx/v_noabi/mongocxx/result/delete.hpp\""
(rm -f "include/mongocxx/v_noabi/mongocxx/result/delete.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/mongocxx/v_noabi/mongocxx/result/insert_many-fwd.hpp\""
(rm -f "include/mongocxx/v_noabi/mongocxx/result/insert_many-fwd.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/mongocxx/v_noabi/mongocxx/result/bulk_write.hpp\""
(rm -f "include/mongocxx/v_noabi/mongocxx/result/bulk_write.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/mongocxx/v_noabi/mongocxx/result/insert_one-fwd.hpp\""
(rm -f "include/mongocxx/v_noabi/mongocxx/result/insert_one-fwd.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/mongocxx/v_noabi/mongocxx/result/delete-fwd.hpp\""
(rm -f "include/mongocxx/v_noabi/mongocxx/result/delete-fwd.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/mongocxx/v_noabi/mongocxx/result/rewrap_many_datakey.hpp\""
(rm -f "include/mongocxx/v_noabi/mongocxx/result/rewrap_many_datakey.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/mongocxx/v_noabi/mongocxx/result/replace_one-fwd.hpp\""
(rm -f "include/mongocxx/v_noabi/mongocxx/result/replace_one-fwd.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/mongocxx/v_noabi/mongocxx/result/insert_one.hpp\""
(rm -f "include/mongocxx/v_noabi/mongocxx/result/insert_one.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/mongocxx/v_noabi/mongocxx/result/gridfs/upload-fwd.hpp\""
(rm -f "include/mongocxx/v_noabi/mongocxx/result/gridfs/upload-fwd.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/mongocxx/v_noabi/mongocxx/result/gridfs/upload.hpp\""
(rm -f "include/mongocxx/v_noabi/mongocxx/result/gridfs/upload.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/mongocxx/v_noabi/mongocxx/result/update-fwd.hpp\""
(rm -f "include/mongocxx/v_noabi/mongocxx/result/update-fwd.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/mongocxx/v_noabi/mongocxx/result/update.hpp\""
(rm -f "include/mongocxx/v_noabi/mongocxx/result/update.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/mongocxx/v_noabi/mongocxx/pool.hpp\""
(rm -f "include/mongocxx/v_noabi/mongocxx/pool.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/mongocxx/v_noabi/mongocxx/read_concern-fwd.hpp\""
(rm -f "include/mongocxx/v_noabi/mongocxx/read_concern-fwd.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/mongocxx/v_noabi/mongocxx/cursor-fwd.hpp\""
(rm -f "include/mongocxx/v_noabi/mongocxx/cursor-fwd.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/mongocxx/v_noabi/mongocxx/client_encryption-fwd.hpp\""
(rm -f "include/mongocxx/v_noabi/mongocxx/client_encryption-fwd.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/mongocxx/v_noabi/mongocxx/bulk_write-fwd.hpp\""
(rm -f "include/mongocxx/v_noabi/mongocxx/bulk_write-fwd.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/mongocxx/v_noabi/mongocxx/search_index_view-fwd.hpp\""
(rm -f "include/mongocxx/v_noabi/mongocxx/search_index_view-fwd.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/mongocxx/v_noabi/mongocxx/validation_criteria.hpp\""
(rm -f "include/mongocxx/v_noabi/mongocxx/validation_criteria.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/mongocxx/v_noabi/mongocxx/write_concern.hpp\""
(rm -f "include/mongocxx/v_noabi/mongocxx/write_concern.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/mongocxx/v_noabi/mongocxx/index_model-fwd.hpp\""
(rm -f "include/mongocxx/v_noabi/mongocxx/index_model-fwd.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/mongocxx/v_noabi/mongocxx/validation_criteria-fwd.hpp\""
(rm -f "include/mongocxx/v_noabi/mongocxx/validation_criteria-fwd.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/mongocxx/v_noabi/mongocxx/write_concern-fwd.hpp\""
(rm -f "include/mongocxx/v_noabi/mongocxx/write_concern-fwd.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/mongocxx/v_noabi/mongocxx/search_index_view.hpp\""
(rm -f "include/mongocxx/v_noabi/mongocxx/search_index_view.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/mongocxx/v_noabi/mongocxx/hint.hpp\""
(rm -f "include/mongocxx/v_noabi/mongocxx/hint.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/mongocxx/v_noabi/mongocxx/database-fwd.hpp\""
(rm -f "include/mongocxx/v_noabi/mongocxx/database-fwd.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/mongocxx/v_noabi/mongocxx/client_session-fwd.hpp\""
(rm -f "include/mongocxx/v_noabi/mongocxx/client_session-fwd.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/mongocxx/v_noabi/mongocxx/read_preference-fwd.hpp\""
(rm -f "include/mongocxx/v_noabi/mongocxx/read_preference-fwd.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/mongocxx/v_noabi/mongocxx/index_view-fwd.hpp\""
(rm -f "include/mongocxx/v_noabi/mongocxx/index_view-fwd.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/mongocxx/v_noabi/mongocxx/change_stream-fwd.hpp\""
(rm -f "include/mongocxx/v_noabi/mongocxx/change_stream-fwd.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/mongocxx/v_noabi/mongocxx/hint-fwd.hpp\""
(rm -f "include/mongocxx/v_noabi/mongocxx/hint-fwd.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/mongocxx/v_noabi/mongocxx/bulk_write.hpp\""
(rm -f "include/mongocxx/v_noabi/mongocxx/bulk_write.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/mongocxx/v_noabi/mongocxx/uri-fwd.hpp\""
(rm -f "include/mongocxx/v_noabi/mongocxx/uri-fwd.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/mongocxx/v_noabi/mongocxx/client_encryption.hpp\""
(rm -f "include/mongocxx/v_noabi/mongocxx/client_encryption.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/mongocxx/v_noabi/mongocxx/exception/exception-fwd.hpp\""
(rm -f "include/mongocxx/v_noabi/mongocxx/exception/exception-fwd.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/mongocxx/v_noabi/mongocxx/exception/query_exception-fwd.hpp\""
(rm -f "include/mongocxx/v_noabi/mongocxx/exception/query_exception-fwd.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/mongocxx/v_noabi/mongocxx/exception/server_error_code-fwd.hpp\""
(rm -f "include/mongocxx/v_noabi/mongocxx/exception/server_error_code-fwd.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/mongocxx/v_noabi/mongocxx/exception/server_error_code.hpp\""
(rm -f "include/mongocxx/v_noabi/mongocxx/exception/server_error_code.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/mongocxx/v_noabi/mongocxx/exception/write_exception-fwd.hpp\""
(rm -f "include/mongocxx/v_noabi/mongocxx/exception/write_exception-fwd.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/mongocxx/v_noabi/mongocxx/exception/authentication_exception.hpp\""
(rm -f "include/mongocxx/v_noabi/mongocxx/exception/authentication_exception.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/mongocxx/v_noabi/mongocxx/exception/authentication_exception-fwd.hpp\""
(rm -f "include/mongocxx/v_noabi/mongocxx/exception/authentication_exception-fwd.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/mongocxx/v_noabi/mongocxx/exception/exception.hpp\""
(rm -f "include/mongocxx/v_noabi/mongocxx/exception/exception.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/mongocxx/v_noabi/mongocxx/exception/operation_exception-fwd.hpp\""
(rm -f "include/mongocxx/v_noabi/mongocxx/exception/operation_exception-fwd.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/mongocxx/v_noabi/mongocxx/exception/logic_error.hpp\""
(rm -f "include/mongocxx/v_noabi/mongocxx/exception/logic_error.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/mongocxx/v_noabi/mongocxx/exception/gridfs_exception-fwd.hpp\""
(rm -f "include/mongocxx/v_noabi/mongocxx/exception/gridfs_exception-fwd.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/mongocxx/v_noabi/mongocxx/exception/operation_exception.hpp\""
(rm -f "include/mongocxx/v_noabi/mongocxx/exception/operation_exception.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/mongocxx/v_noabi/mongocxx/exception/logic_error-fwd.hpp\""
(rm -f "include/mongocxx/v_noabi/mongocxx/exception/logic_error-fwd.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/mongocxx/v_noabi/mongocxx/exception/error_code.hpp\""
(rm -f "include/mongocxx/v_noabi/mongocxx/exception/error_code.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/mongocxx/v_noabi/mongocxx/exception/gridfs_exception.hpp\""
(rm -f "include/mongocxx/v_noabi/mongocxx/exception/gridfs_exception.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/mongocxx/v_noabi/mongocxx/exception/write_exception.hpp\""
(rm -f "include/mongocxx/v_noabi/mongocxx/exception/write_exception.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/mongocxx/v_noabi/mongocxx/exception/bulk_write_exception.hpp\""
(rm -f "include/mongocxx/v_noabi/mongocxx/exception/bulk_write_exception.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/mongocxx/v_noabi/mongocxx/exception/query_exception.hpp\""
(rm -f "include/mongocxx/v_noabi/mongocxx/exception/query_exception.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/mongocxx/v_noabi/mongocxx/exception/bulk_write_exception-fwd.hpp\""
(rm -f "include/mongocxx/v_noabi/mongocxx/exception/bulk_write_exception-fwd.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/mongocxx/v_noabi/mongocxx/exception/error_code-fwd.hpp\""
(rm -f "include/mongocxx/v_noabi/mongocxx/exception/error_code-fwd.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/mongocxx/v_noabi/mongocxx/logger-fwd.hpp\""
(rm -f "include/mongocxx/v_noabi/mongocxx/logger-fwd.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/mongocxx/v_noabi/mongocxx/client_session.hpp\""
(rm -f "include/mongocxx/v_noabi/mongocxx/client_session.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/mongocxx/v_noabi/mongocxx/pool-fwd.hpp\""
(rm -f "include/mongocxx/v_noabi/mongocxx/pool-fwd.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/mongocxx/v_noabi/mongocxx/model/replace_one.hpp\""
(rm -f "include/mongocxx/v_noabi/mongocxx/model/replace_one.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/mongocxx/v_noabi/mongocxx/model/update_many-fwd.hpp\""
(rm -f "include/mongocxx/v_noabi/mongocxx/model/update_many-fwd.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/mongocxx/v_noabi/mongocxx/model/delete_one-fwd.hpp\""
(rm -f "include/mongocxx/v_noabi/mongocxx/model/delete_one-fwd.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/mongocxx/v_noabi/mongocxx/model/delete_many.hpp\""
(rm -f "include/mongocxx/v_noabi/mongocxx/model/delete_many.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/mongocxx/v_noabi/mongocxx/model/write.hpp\""
(rm -f "include/mongocxx/v_noabi/mongocxx/model/write.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/mongocxx/v_noabi/mongocxx/model/insert_one-fwd.hpp\""
(rm -f "include/mongocxx/v_noabi/mongocxx/model/insert_one-fwd.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/mongocxx/v_noabi/mongocxx/model/delete_many-fwd.hpp\""
(rm -f "include/mongocxx/v_noabi/mongocxx/model/delete_many-fwd.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/mongocxx/v_noabi/mongocxx/model/update_many.hpp\""
(rm -f "include/mongocxx/v_noabi/mongocxx/model/update_many.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/mongocxx/v_noabi/mongocxx/model/replace_one-fwd.hpp\""
(rm -f "include/mongocxx/v_noabi/mongocxx/model/replace_one-fwd.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/mongocxx/v_noabi/mongocxx/model/write-fwd.hpp\""
(rm -f "include/mongocxx/v_noabi/mongocxx/model/write-fwd.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/mongocxx/v_noabi/mongocxx/model/update_one.hpp\""
(rm -f "include/mongocxx/v_noabi/mongocxx/model/update_one.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/mongocxx/v_noabi/mongocxx/model/delete_one.hpp\""
(rm -f "include/mongocxx/v_noabi/mongocxx/model/delete_one.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/mongocxx/v_noabi/mongocxx/model/insert_one.hpp\""
(rm -f "include/mongocxx/v_noabi/mongocxx/model/insert_one.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/mongocxx/v_noabi/mongocxx/model/update_one-fwd.hpp\""
(rm -f "include/mongocxx/v_noabi/mongocxx/model/update_one-fwd.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/mongocxx/v_noabi/mongocxx/events/topology_opening_event-fwd.hpp\""
(rm -f "include/mongocxx/v_noabi/mongocxx/events/topology_opening_event-fwd.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/mongocxx/v_noabi/mongocxx/events/topology_closed_event.hpp\""
(rm -f "include/mongocxx/v_noabi/mongocxx/events/topology_closed_event.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/mongocxx/v_noabi/mongocxx/events/command_succeeded_event.hpp\""
(rm -f "include/mongocxx/v_noabi/mongocxx/events/command_succeeded_event.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/mongocxx/v_noabi/mongocxx/events/heartbeat_succeeded_event.hpp\""
(rm -f "include/mongocxx/v_noabi/mongocxx/events/heartbeat_succeeded_event.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/mongocxx/v_noabi/mongocxx/events/topology_changed_event.hpp\""
(rm -f "include/mongocxx/v_noabi/mongocxx/events/topology_changed_event.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/mongocxx/v_noabi/mongocxx/events/topology_description.hpp\""
(rm -f "include/mongocxx/v_noabi/mongocxx/events/topology_description.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/mongocxx/v_noabi/mongocxx/events/server_changed_event-fwd.hpp\""
(rm -f "include/mongocxx/v_noabi/mongocxx/events/server_changed_event-fwd.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/mongocxx/v_noabi/mongocxx/events/server_closed_event-fwd.hpp\""
(rm -f "include/mongocxx/v_noabi/mongocxx/events/server_closed_event-fwd.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/mongocxx/v_noabi/mongocxx/events/heartbeat_started_event-fwd.hpp\""
(rm -f "include/mongocxx/v_noabi/mongocxx/events/heartbeat_started_event-fwd.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/mongocxx/v_noabi/mongocxx/events/topology_opening_event.hpp\""
(rm -f "include/mongocxx/v_noabi/mongocxx/events/topology_opening_event.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/mongocxx/v_noabi/mongocxx/events/command_succeeded_event-fwd.hpp\""
(rm -f "include/mongocxx/v_noabi/mongocxx/events/command_succeeded_event-fwd.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/mongocxx/v_noabi/mongocxx/events/command_started_event-fwd.hpp\""
(rm -f "include/mongocxx/v_noabi/mongocxx/events/command_started_event-fwd.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/mongocxx/v_noabi/mongocxx/events/heartbeat_failed_event-fwd.hpp\""
(rm -f "include/mongocxx/v_noabi/mongocxx/events/heartbeat_failed_event-fwd.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/mongocxx/v_noabi/mongocxx/events/server_description-fwd.hpp\""
(rm -f "include/mongocxx/v_noabi/mongocxx/events/server_description-fwd.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/mongocxx/v_noabi/mongocxx/events/server_opening_event-fwd.hpp\""
(rm -f "include/mongocxx/v_noabi/mongocxx/events/server_opening_event-fwd.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/mongocxx/v_noabi/mongocxx/events/heartbeat_started_event.hpp\""
(rm -f "include/mongocxx/v_noabi/mongocxx/events/heartbeat_started_event.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/mongocxx/v_noabi/mongocxx/events/heartbeat_failed_event.hpp\""
(rm -f "include/mongocxx/v_noabi/mongocxx/events/heartbeat_failed_event.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/mongocxx/v_noabi/mongocxx/events/command_started_event.hpp\""
(rm -f "include/mongocxx/v_noabi/mongocxx/events/command_started_event.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/mongocxx/v_noabi/mongocxx/events/heartbeat_succeeded_event-fwd.hpp\""
(rm -f "include/mongocxx/v_noabi/mongocxx/events/heartbeat_succeeded_event-fwd.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/mongocxx/v_noabi/mongocxx/events/topology_description-fwd.hpp\""
(rm -f "include/mongocxx/v_noabi/mongocxx/events/topology_description-fwd.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/mongocxx/v_noabi/mongocxx/events/command_failed_event-fwd.hpp\""
(rm -f "include/mongocxx/v_noabi/mongocxx/events/command_failed_event-fwd.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/mongocxx/v_noabi/mongocxx/events/command_failed_event.hpp\""
(rm -f "include/mongocxx/v_noabi/mongocxx/events/command_failed_event.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/mongocxx/v_noabi/mongocxx/events/server_closed_event.hpp\""
(rm -f "include/mongocxx/v_noabi/mongocxx/events/server_closed_event.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/mongocxx/v_noabi/mongocxx/events/topology_changed_event-fwd.hpp\""
(rm -f "include/mongocxx/v_noabi/mongocxx/events/topology_changed_event-fwd.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/mongocxx/v_noabi/mongocxx/events/topology_closed_event-fwd.hpp\""
(rm -f "include/mongocxx/v_noabi/mongocxx/events/topology_closed_event-fwd.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/mongocxx/v_noabi/mongocxx/events/server_opening_event.hpp\""
(rm -f "include/mongocxx/v_noabi/mongocxx/events/server_opening_event.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/mongocxx/v_noabi/mongocxx/events/server_description.hpp\""
(rm -f "include/mongocxx/v_noabi/mongocxx/events/server_description.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/mongocxx/v_noabi/mongocxx/events/server_changed_event.hpp\""
(rm -f "include/mongocxx/v_noabi/mongocxx/events/server_changed_event.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/mongocxx/v_noabi/mongocxx/search_index_model-fwd.hpp\""
(rm -f "include/mongocxx/v_noabi/mongocxx/search_index_model-fwd.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/mongocxx/v_noabi/mongocxx/uri.hpp\""
(rm -f "include/mongocxx/v_noabi/mongocxx/uri.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/mongocxx/v_noabi/mongocxx/fwd.hpp\""
(rm -f "include/mongocxx/v_noabi/mongocxx/fwd.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/mongocxx/v_noabi/mongocxx/pipeline-fwd.hpp\""
(rm -f "include/mongocxx/v_noabi/mongocxx/pipeline-fwd.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/mongocxx/v_noabi/mongocxx/config/prelude.hpp\""
(rm -f "include/mongocxx/v_noabi/mongocxx/config/prelude.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/mongocxx/v_noabi/mongocxx/config/postlude.hpp\""
(rm -f "include/mongocxx/v_noabi/mongocxx/config/postlude.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/mongocxx/v_noabi/mongocxx/config/compiler.hpp\""
(rm -f "include/mongocxx/v_noabi/mongocxx/config/compiler.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/mongocxx/v_noabi/mongocxx/index_view.hpp\""
(rm -f "include/mongocxx/v_noabi/mongocxx/index_view.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/mongocxx/v_noabi/mongocxx/client-fwd.hpp\""
(rm -f "include/mongocxx/v_noabi/mongocxx/client-fwd.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/mongocxx/v_noabi/mongocxx/client.hpp\""
(rm -f "include/mongocxx/v_noabi/mongocxx/client.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/mongocxx/v_noabi/mongocxx/change_stream.hpp\""
(rm -f "include/mongocxx/v_noabi/mongocxx/change_stream.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/mongocxx/v_noabi/mongocxx/logger.hpp\""
(rm -f "include/mongocxx/v_noabi/mongocxx/logger.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/mongocxx/v_noabi/mongocxx/write_type-fwd.hpp\""
(rm -f "include/mongocxx/v_noabi/mongocxx/write_type-fwd.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/mongocxx/v_noabi/mongocxx/collection-fwd.hpp\""
(rm -f "include/mongocxx/v_noabi/mongocxx/collection-fwd.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/mongocxx/v_noabi/mongocxx/instance-fwd.hpp\""
(rm -f "include/mongocxx/v_noabi/mongocxx/instance-fwd.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/mongocxx/v_noabi/mongocxx/index_model.hpp\""
(rm -f "include/mongocxx/v_noabi/mongocxx/index_model.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/mongocxx/v_noabi/mongocxx/pipeline.hpp\""
(rm -f "include/mongocxx/v_noabi/mongocxx/pipeline.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/mongocxx/v_noabi/mongocxx/read_concern.hpp\""
(rm -f "include/mongocxx/v_noabi/mongocxx/read_concern.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/mongocxx/v_noabi/mongocxx/collection.hpp\""
(rm -f "include/mongocxx/v_noabi/mongocxx/collection.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/mongocxx/v_noabi/mongocxx/gridfs/uploader.hpp\""
(rm -f "include/mongocxx/v_noabi/mongocxx/gridfs/uploader.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/mongocxx/v_noabi/mongocxx/gridfs/uploader-fwd.hpp\""
(rm -f "include/mongocxx/v_noabi/mongocxx/gridfs/uploader-fwd.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/mongocxx/v_noabi/mongocxx/gridfs/downloader-fwd.hpp\""
(rm -f "include/mongocxx/v_noabi/mongocxx/gridfs/downloader-fwd.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/mongocxx/v_noabi/mongocxx/gridfs/bucket.hpp\""
(rm -f "include/mongocxx/v_noabi/mongocxx/gridfs/bucket.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/mongocxx/v_noabi/mongocxx/gridfs/bucket-fwd.hpp\""
(rm -f "include/mongocxx/v_noabi/mongocxx/gridfs/bucket-fwd.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/mongocxx/v_noabi/mongocxx/gridfs/downloader.hpp\""
(rm -f "include/mongocxx/v_noabi/mongocxx/gridfs/downloader.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/mongocxx/v_noabi/mongocxx/read_preference.hpp\""
(rm -f "include/mongocxx/v_noabi/mongocxx/read_preference.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/mongocxx/v_noabi/mongocxx/options/find_one_common_options-fwd.hpp\""
(rm -f "include/mongocxx/v_noabi/mongocxx/options/find_one_common_options-fwd.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/mongocxx/v_noabi/mongocxx/options/server_api.hpp\""
(rm -f "include/mongocxx/v_noabi/mongocxx/options/server_api.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/mongocxx/v_noabi/mongocxx/options/distinct-fwd.hpp\""
(rm -f "include/mongocxx/v_noabi/mongocxx/options/distinct-fwd.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/mongocxx/v_noabi/mongocxx/options/rewrap_many_datakey-fwd.hpp\""
(rm -f "include/mongocxx/v_noabi/mongocxx/options/rewrap_many_datakey-fwd.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/mongocxx/v_noabi/mongocxx/options/find_one_and_update.hpp\""
(rm -f "include/mongocxx/v_noabi/mongocxx/options/find_one_and_update.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/mongocxx/v_noabi/mongocxx/options/find_one_and_delete-fwd.hpp\""
(rm -f "include/mongocxx/v_noabi/mongocxx/options/find_one_and_delete-fwd.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/mongocxx/v_noabi/mongocxx/options/apm.hpp\""
(rm -f "include/mongocxx/v_noabi/mongocxx/options/apm.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/mongocxx/v_noabi/mongocxx/options/insert-fwd.hpp\""
(rm -f "include/mongocxx/v_noabi/mongocxx/options/insert-fwd.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/mongocxx/v_noabi/mongocxx/options/pool.hpp\""
(rm -f "include/mongocxx/v_noabi/mongocxx/options/pool.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/mongocxx/v_noabi/mongocxx/options/count.hpp\""
(rm -f "include/mongocxx/v_noabi/mongocxx/options/count.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/mongocxx/v_noabi/mongocxx/options/range-fwd.hpp\""
(rm -f "include/mongocxx/v_noabi/mongocxx/options/range-fwd.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/mongocxx/v_noabi/mongocxx/options/ssl.hpp\""
(rm -f "include/mongocxx/v_noabi/mongocxx/options/ssl.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/mongocxx/v_noabi/mongocxx/options/replace.hpp\""
(rm -f "include/mongocxx/v_noabi/mongocxx/options/replace.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/mongocxx/v_noabi/mongocxx/options/auto_encryption.hpp\""
(rm -f "include/mongocxx/v_noabi/mongocxx/options/auto_encryption.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/mongocxx/v_noabi/mongocxx/options/client_encryption-fwd.hpp\""
(rm -f "include/mongocxx/v_noabi/mongocxx/options/client_encryption-fwd.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/mongocxx/v_noabi/mongocxx/options/find_one_common_options.hpp\""
(rm -f "include/mongocxx/v_noabi/mongocxx/options/find_one_common_options.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/mongocxx/v_noabi/mongocxx/options/bulk_write-fwd.hpp\""
(rm -f "include/mongocxx/v_noabi/mongocxx/options/bulk_write-fwd.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/mongocxx/v_noabi/mongocxx/options/delete.hpp\""
(rm -f "include/mongocxx/v_noabi/mongocxx/options/delete.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/mongocxx/v_noabi/mongocxx/options/encrypt-fwd.hpp\""
(rm -f "include/mongocxx/v_noabi/mongocxx/options/encrypt-fwd.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/mongocxx/v_noabi/mongocxx/options/find.hpp\""
(rm -f "include/mongocxx/v_noabi/mongocxx/options/find.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/mongocxx/v_noabi/mongocxx/options/find_one_and_delete.hpp\""
(rm -f "include/mongocxx/v_noabi/mongocxx/options/find_one_and_delete.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/mongocxx/v_noabi/mongocxx/options/aggregate-fwd.hpp\""
(rm -f "include/mongocxx/v_noabi/mongocxx/options/aggregate-fwd.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/mongocxx/v_noabi/mongocxx/options/client_session-fwd.hpp\""
(rm -f "include/mongocxx/v_noabi/mongocxx/options/client_session-fwd.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/mongocxx/v_noabi/mongocxx/options/encrypt.hpp\""
(rm -f "include/mongocxx/v_noabi/mongocxx/options/encrypt.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/mongocxx/v_noabi/mongocxx/options/index_view-fwd.hpp\""
(rm -f "include/mongocxx/v_noabi/mongocxx/options/index_view-fwd.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/mongocxx/v_noabi/mongocxx/options/find-fwd.hpp\""
(rm -f "include/mongocxx/v_noabi/mongocxx/options/find-fwd.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/mongocxx/v_noabi/mongocxx/options/change_stream-fwd.hpp\""
(rm -f "include/mongocxx/v_noabi/mongocxx/options/change_stream-fwd.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/mongocxx/v_noabi/mongocxx/options/bulk_write.hpp\""
(rm -f "include/mongocxx/v_noabi/mongocxx/options/bulk_write.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/mongocxx/v_noabi/mongocxx/options/client_encryption.hpp\""
(rm -f "include/mongocxx/v_noabi/mongocxx/options/client_encryption.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/mongocxx/v_noabi/mongocxx/options/client_session.hpp\""
(rm -f "include/mongocxx/v_noabi/mongocxx/options/client_session.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/mongocxx/v_noabi/mongocxx/options/pool-fwd.hpp\""
(rm -f "include/mongocxx/v_noabi/mongocxx/options/pool-fwd.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/mongocxx/v_noabi/mongocxx/options/create_collection.hpp\""
(rm -f "include/mongocxx/v_noabi/mongocxx/options/create_collection.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/mongocxx/v_noabi/mongocxx/options/distinct.hpp\""
(rm -f "include/mongocxx/v_noabi/mongocxx/options/distinct.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/mongocxx/v_noabi/mongocxx/options/server_api-fwd.hpp\""
(rm -f "include/mongocxx/v_noabi/mongocxx/options/server_api-fwd.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/mongocxx/v_noabi/mongocxx/options/aggregate.hpp\""
(rm -f "include/mongocxx/v_noabi/mongocxx/options/aggregate.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/mongocxx/v_noabi/mongocxx/options/delete-fwd.hpp\""
(rm -f "include/mongocxx/v_noabi/mongocxx/options/delete-fwd.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/mongocxx/v_noabi/mongocxx/options/auto_encryption-fwd.hpp\""
(rm -f "include/mongocxx/v_noabi/mongocxx/options/auto_encryption-fwd.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/mongocxx/v_noabi/mongocxx/options/count-fwd.hpp\""
(rm -f "include/mongocxx/v_noabi/mongocxx/options/count-fwd.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/mongocxx/v_noabi/mongocxx/options/rewrap_many_datakey.hpp\""
(rm -f "include/mongocxx/v_noabi/mongocxx/options/rewrap_many_datakey.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/mongocxx/v_noabi/mongocxx/options/range.hpp\""
(rm -f "include/mongocxx/v_noabi/mongocxx/options/range.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/mongocxx/v_noabi/mongocxx/options/data_key.hpp\""
(rm -f "include/mongocxx/v_noabi/mongocxx/options/data_key.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/mongocxx/v_noabi/mongocxx/options/transaction-fwd.hpp\""
(rm -f "include/mongocxx/v_noabi/mongocxx/options/transaction-fwd.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/mongocxx/v_noabi/mongocxx/options/apm-fwd.hpp\""
(rm -f "include/mongocxx/v_noabi/mongocxx/options/apm-fwd.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/mongocxx/v_noabi/mongocxx/options/tls.hpp\""
(rm -f "include/mongocxx/v_noabi/mongocxx/options/tls.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/mongocxx/v_noabi/mongocxx/options/tls-fwd.hpp\""
(rm -f "include/mongocxx/v_noabi/mongocxx/options/tls-fwd.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/mongocxx/v_noabi/mongocxx/options/index_view.hpp\""
(rm -f "include/mongocxx/v_noabi/mongocxx/options/index_view.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/mongocxx/v_noabi/mongocxx/options/client-fwd.hpp\""
(rm -f "include/mongocxx/v_noabi/mongocxx/options/client-fwd.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/mongocxx/v_noabi/mongocxx/options/client.hpp\""
(rm -f "include/mongocxx/v_noabi/mongocxx/options/client.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/mongocxx/v_noabi/mongocxx/options/index.hpp\""
(rm -f "include/mongocxx/v_noabi/mongocxx/options/index.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/mongocxx/v_noabi/mongocxx/options/change_stream.hpp\""
(rm -f "include/mongocxx/v_noabi/mongocxx/options/change_stream.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/mongocxx/v_noabi/mongocxx/options/estimated_document_count.hpp\""
(rm -f "include/mongocxx/v_noabi/mongocxx/options/estimated_document_count.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/mongocxx/v_noabi/mongocxx/options/insert.hpp\""
(rm -f "include/mongocxx/v_noabi/mongocxx/options/insert.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/mongocxx/v_noabi/mongocxx/options/find_one_and_update-fwd.hpp\""
(rm -f "include/mongocxx/v_noabi/mongocxx/options/find_one_and_update-fwd.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/mongocxx/v_noabi/mongocxx/options/data_key-fwd.hpp\""
(rm -f "include/mongocxx/v_noabi/mongocxx/options/data_key-fwd.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/mongocxx/v_noabi/mongocxx/options/find_one_and_replace.hpp\""
(rm -f "include/mongocxx/v_noabi/mongocxx/options/find_one_and_replace.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/mongocxx/v_noabi/mongocxx/options/find_one_and_replace-fwd.hpp\""
(rm -f "include/mongocxx/v_noabi/mongocxx/options/find_one_and_replace-fwd.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/mongocxx/v_noabi/mongocxx/options/replace-fwd.hpp\""
(rm -f "include/mongocxx/v_noabi/mongocxx/options/replace-fwd.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/mongocxx/v_noabi/mongocxx/options/gridfs/bucket.hpp\""
(rm -f "include/mongocxx/v_noabi/mongocxx/options/gridfs/bucket.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/mongocxx/v_noabi/mongocxx/options/gridfs/bucket-fwd.hpp\""
(rm -f "include/mongocxx/v_noabi/mongocxx/options/gridfs/bucket-fwd.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/mongocxx/v_noabi/mongocxx/options/gridfs/upload-fwd.hpp\""
(rm -f "include/mongocxx/v_noabi/mongocxx/options/gridfs/upload-fwd.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/mongocxx/v_noabi/mongocxx/options/gridfs/upload.hpp\""
(rm -f "include/mongocxx/v_noabi/mongocxx/options/gridfs/upload.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/mongocxx/v_noabi/mongocxx/options/index-fwd.hpp\""
(rm -f "include/mongocxx/v_noabi/mongocxx/options/index-fwd.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/mongocxx/v_noabi/mongocxx/options/update-fwd.hpp\""
(rm -f "include/mongocxx/v_noabi/mongocxx/options/update-fwd.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/mongocxx/v_noabi/mongocxx/options/estimated_document_count-fwd.hpp\""
(rm -f "include/mongocxx/v_noabi/mongocxx/options/estimated_document_count-fwd.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/mongocxx/v_noabi/mongocxx/options/update.hpp\""
(rm -f "include/mongocxx/v_noabi/mongocxx/options/update.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/mongocxx/v_noabi/mongocxx/options/transaction.hpp\""
(rm -f "include/mongocxx/v_noabi/mongocxx/options/transaction.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/mongocxx/v_noabi/mongocxx/instance.hpp\""
(rm -f "include/mongocxx/v_noabi/mongocxx/instance.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/mongocxx/v_noabi/mongocxx/search_index_model.hpp\""
(rm -f "include/mongocxx/v_noabi/mongocxx/search_index_model.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/mongocxx/v_noabi/mongocxx/database.hpp\""
(rm -f "include/mongocxx/v_noabi/mongocxx/database.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/mongocxx/v_noabi/mongocxx/config/config.hpp\""
(rm -f "include/mongocxx/v_noabi/mongocxx/config/config.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/mongocxx/v_noabi/mongocxx/config/version.hpp\""
(rm -f "include/mongocxx/v_noabi/mongocxx/config/version.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"include/mongocxx/v_noabi/mongocxx/config/export.hpp\""
(rm -f "include/mongocxx/v_noabi/mongocxx/config/export.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"lib/libmongocxx.so.3.10.1\""
(rm -f "lib/libmongocxx.so.3.10.1" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"lib/libmongocxx.so._noabi\""
(rm -f "lib/libmongocxx.so._noabi" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"lib/libmongocxx.so\""
(rm -f "lib/libmongocxx.so" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"lib/cmake/mongocxx-3.10.1/mongocxx_targets.cmake\""
(rm -f "lib/cmake/mongocxx-3.10.1/mongocxx_targets.cmake" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"lib/cmake/mongocxx-3.10.1/mongocxx_targets-release.cmake\""
(rm -f "lib/cmake/mongocxx-3.10.1/mongocxx_targets-release.cmake" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"lib/cmake/mongocxx-3.10.1/mongocxx-config-version.cmake\""
(rm -f "lib/cmake/mongocxx-3.10.1/mongocxx-config-version.cmake" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"lib/cmake/mongocxx-3.10.1/mongocxx-config.cmake\""
(rm -f "lib/cmake/mongocxx-3.10.1/mongocxx-config.cmake" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"lib/pkgconfig/libmongocxx.pc\""
(rm -f "lib/pkgconfig/libmongocxx.pc" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"share/mongo-cxx-driver/LICENSE\""
(rm -f "share/mongo-cxx-driver/LICENSE" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"share/mongo-cxx-driver/README.md\""
(rm -f "share/mongo-cxx-driver/README.md" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"share/mongo-cxx-driver/THIRD-PARTY-NOTICES\""
(rm -f "share/mongo-cxx-driver/THIRD-PARTY-NOTICES" && printf "\n") || printf " ... not removed\n"
printf "Removing file \"share/mongo-cxx-driver/uninstall.sh\""
(rm -f "share/mongo-cxx-driver/uninstall.sh" && printf "\n") || printf " ... not removed\n"
printf "Removing directory \"share/mongo-cxx-driver\""
(rmdir "share/mongo-cxx-driver" 2>/dev/null && printf "\n") || printf " ... not removed (probably not empty)\n"
printf "Removing directory \"share/mongo-c-driver\""
(rmdir "share/mongo-c-driver" 2>/dev/null && printf "\n") || printf " ... not removed (probably not empty)\n"
printf "Removing directory \"share\""
(rmdir "share" 2>/dev/null && printf "\n") || printf " ... not removed (probably not empty)\n"
printf "Removing directory \"lib/pkgconfig\""
(rmdir "lib/pkgconfig" 2>/dev/null && printf "\n") || printf " ... not removed (probably not empty)\n"
printf "Removing directory \"lib/cmake/mongocxx-3.10.1\""
(rmdir "lib/cmake/mongocxx-3.10.1" 2>/dev/null && printf "\n") || printf " ... not removed (probably not empty)\n"
printf "Removing directory \"lib/cmake/mongoc-1.0\""
(rmdir "lib/cmake/mongoc-1.0" 2>/dev/null && printf "\n") || printf " ... not removed (probably not empty)\n"
printf "Removing directory \"lib/cmake/libmongoc-static-1.0\""
(rmdir "lib/cmake/libmongoc-static-1.0" 2>/dev/null && printf "\n") || printf " ... not removed (probably not empty)\n"
printf "Removing directory \"lib/cmake/libmongoc-1.0\""
(rmdir "lib/cmake/libmongoc-1.0" 2>/dev/null && printf "\n") || printf " ... not removed (probably not empty)\n"
printf "Removing directory \"lib/cmake/libbson-static-1.0\""
(rmdir "lib/cmake/libbson-static-1.0" 2>/dev/null && printf "\n") || printf " ... not removed (probably not empty)\n"
printf "Removing directory \"lib/cmake/libbson-1.0\""
(rmdir "lib/cmake/libbson-1.0" 2>/dev/null && printf "\n") || printf " ... not removed (probably not empty)\n"
printf "Removing directory \"lib/cmake/bsoncxx-3.10.1\""
(rmdir "lib/cmake/bsoncxx-3.10.1" 2>/dev/null && printf "\n") || printf " ... not removed (probably not empty)\n"
printf "Removing directory \"lib/cmake/bson-1.0\""
(rmdir "lib/cmake/bson-1.0" 2>/dev/null && printf "\n") || printf " ... not removed (probably not empty)\n"
printf "Removing directory \"lib/cmake\""
(rmdir "lib/cmake" 2>/dev/null && printf "\n") || printf " ... not removed (probably not empty)\n"
printf "Removing directory \"lib\""
(rmdir "lib" 2>/dev/null && printf "\n") || printf " ... not removed (probably not empty)\n"
printf "Removing directory \"include/mongocxx/v_noabi/mongocxx/result/gridfs\""
(rmdir "include/mongocxx/v_noabi/mongocxx/result/gridfs" 2>/dev/null && printf "\n") || printf " ... not removed (probably not empty)\n"
printf "Removing directory \"include/mongocxx/v_noabi/mongocxx/result\""
(rmdir "include/mongocxx/v_noabi/mongocxx/result" 2>/dev/null && printf "\n") || printf " ... not removed (probably not empty)\n"
printf "Removing directory \"include/mongocxx/v_noabi/mongocxx/options/gridfs\""
(rmdir "include/mongocxx/v_noabi/mongocxx/options/gridfs" 2>/dev/null && printf "\n") || printf " ... not removed (probably not empty)\n"
printf "Removing directory \"include/mongocxx/v_noabi/mongocxx/options\""
(rmdir "include/mongocxx/v_noabi/mongocxx/options" 2>/dev/null && printf "\n") || printf " ... not removed (probably not empty)\n"
printf "Removing directory \"include/mongocxx/v_noabi/mongocxx/model\""
(rmdir "include/mongocxx/v_noabi/mongocxx/model" 2>/dev/null && printf "\n") || printf " ... not removed (probably not empty)\n"
printf "Removing directory \"include/mongocxx/v_noabi/mongocxx/gridfs\""
(rmdir "include/mongocxx/v_noabi/mongocxx/gridfs" 2>/dev/null && printf "\n") || printf " ... not removed (probably not empty)\n"
printf "Removing directory \"include/mongocxx/v_noabi/mongocxx/exception\""
(rmdir "include/mongocxx/v_noabi/mongocxx/exception" 2>/dev/null && printf "\n") || printf " ... not removed (probably not empty)\n"
printf "Removing directory \"include/mongocxx/v_noabi/mongocxx/events\""
(rmdir "include/mongocxx/v_noabi/mongocxx/events" 2>/dev/null && printf "\n") || printf " ... not removed (probably not empty)\n"
printf "Removing directory \"include/mongocxx/v_noabi/mongocxx/config\""
(rmdir "include/mongocxx/v_noabi/mongocxx/config" 2>/dev/null && printf "\n") || printf " ... not removed (probably not empty)\n"
printf "Removing directory \"include/mongocxx/v_noabi/mongocxx\""
(rmdir "include/mongocxx/v_noabi/mongocxx" 2>/dev/null && printf "\n") || printf " ... not removed (probably not empty)\n"
printf "Removing directory \"include/mongocxx/v_noabi\""
(rmdir "include/mongocxx/v_noabi" 2>/dev/null && printf "\n") || printf " ... not removed (probably not empty)\n"
printf "Removing directory \"include/mongocxx\""
(rmdir "include/mongocxx" 2>/dev/null && printf "\n") || printf " ... not removed (probably not empty)\n"
printf "Removing directory \"include/libmongoc-1.0/mongoc\""
(rmdir "include/libmongoc-1.0/mongoc" 2>/dev/null && printf "\n") || printf " ... not removed (probably not empty)\n"
printf "Removing directory \"include/libmongoc-1.0\""
(rmdir "include/libmongoc-1.0" 2>/dev/null && printf "\n") || printf " ... not removed (probably not empty)\n"
printf "Removing directory \"include/libbson-1.0/bson\""
(rmdir "include/libbson-1.0/bson" 2>/dev/null && printf "\n") || printf " ... not removed (probably not empty)\n"
printf "Removing directory \"include/libbson-1.0\""
(rmdir "include/libbson-1.0" 2>/dev/null && printf "\n") || printf " ... not removed (probably not empty)\n"
printf "Removing directory \"include/bsoncxx/v_noabi/bsoncxx/util\""
(rmdir "include/bsoncxx/v_noabi/bsoncxx/util" 2>/dev/null && printf "\n") || printf " ... not removed (probably not empty)\n"
printf "Removing directory \"include/bsoncxx/v_noabi/bsoncxx/types/bson_value\""
(rmdir "include/bsoncxx/v_noabi/bsoncxx/types/bson_value" 2>/dev/null && printf "\n") || printf " ... not removed (probably not empty)\n"
printf "Removing directory \"include/bsoncxx/v_noabi/bsoncxx/types\""
(rmdir "include/bsoncxx/v_noabi/bsoncxx/types" 2>/dev/null && printf "\n") || printf " ... not removed (probably not empty)\n"
printf "Removing directory \"include/bsoncxx/v_noabi/bsoncxx/third_party/mnmlstc/core\""
(rmdir "include/bsoncxx/v_noabi/bsoncxx/third_party/mnmlstc/core" 2>/dev/null && printf "\n") || printf " ... not removed (probably not empty)\n"
printf "Removing directory \"include/bsoncxx/v_noabi/bsoncxx/third_party/mnmlstc\""
(rmdir "include/bsoncxx/v_noabi/bsoncxx/third_party/mnmlstc" 2>/dev/null && printf "\n") || printf " ... not removed (probably not empty)\n"
printf "Removing directory \"include/bsoncxx/v_noabi/bsoncxx/third_party\""
(rmdir "include/bsoncxx/v_noabi/bsoncxx/third_party" 2>/dev/null && printf "\n") || printf " ... not removed (probably not empty)\n"
printf "Removing directory \"include/bsoncxx/v_noabi/bsoncxx/string\""
(rmdir "include/bsoncxx/v_noabi/bsoncxx/string" 2>/dev/null && printf "\n") || printf " ... not removed (probably not empty)\n"
printf "Removing directory \"include/bsoncxx/v_noabi/bsoncxx/stdx\""
(rmdir "include/bsoncxx/v_noabi/bsoncxx/stdx" 2>/dev/null && printf "\n") || printf " ... not removed (probably not empty)\n"
printf "Removing directory \"include/bsoncxx/v_noabi/bsoncxx/exception\""
(rmdir "include/bsoncxx/v_noabi/bsoncxx/exception" 2>/dev/null && printf "\n") || printf " ... not removed (probably not empty)\n"
printf "Removing directory \"include/bsoncxx/v_noabi/bsoncxx/enums\""
(rmdir "include/bsoncxx/v_noabi/bsoncxx/enums" 2>/dev/null && printf "\n") || printf " ... not removed (probably not empty)\n"
printf "Removing directory \"include/bsoncxx/v_noabi/bsoncxx/document\""
(rmdir "include/bsoncxx/v_noabi/bsoncxx/document" 2>/dev/null && printf "\n") || printf " ... not removed (probably not empty)\n"
printf "Removing directory \"include/bsoncxx/v_noabi/bsoncxx/config\""
(rmdir "include/bsoncxx/v_noabi/bsoncxx/config" 2>/dev/null && printf "\n") || printf " ... not removed (probably not empty)\n"
printf "Removing directory \"include/bsoncxx/v_noabi/bsoncxx/builder/stream\""
(rmdir "include/bsoncxx/v_noabi/bsoncxx/builder/stream" 2>/dev/null && printf "\n") || printf " ... not removed (probably not empty)\n"
printf "Removing directory \"include/bsoncxx/v_noabi/bsoncxx/builder/basic\""
(rmdir "include/bsoncxx/v_noabi/bsoncxx/builder/basic" 2>/dev/null && printf "\n") || printf " ... not removed (probably not empty)\n"
printf "Removing directory \"include/bsoncxx/v_noabi/bsoncxx/builder\""
(rmdir "include/bsoncxx/v_noabi/bsoncxx/builder" 2>/dev/null && printf "\n") || printf " ... not removed (probably not empty)\n"
printf "Removing directory \"include/bsoncxx/v_noabi/bsoncxx/array\""
(rmdir "include/bsoncxx/v_noabi/bsoncxx/array" 2>/dev/null && printf "\n") || printf " ... not removed (probably not empty)\n"
printf "Removing directory \"include/bsoncxx/v_noabi/bsoncxx\""
(rmdir "include/bsoncxx/v_noabi/bsoncxx" 2>/dev/null && printf "\n") || printf " ... not removed (probably not empty)\n"
printf "Removing directory \"include/bsoncxx/v_noabi\""
(rmdir "include/bsoncxx/v_noabi" 2>/dev/null && printf "\n") || printf " ... not removed (probably not empty)\n"
printf "Removing directory \"include/bsoncxx\""
(rmdir "include/bsoncxx" 2>/dev/null && printf "\n") || printf " ... not removed (probably not empty)\n"
printf "Removing directory \"include\""
(rmdir "include" 2>/dev/null && printf "\n") || printf " ... not removed (probably not empty)\n"
printf "Removing directory \"bin\""
(rmdir "bin" 2>/dev/null && printf "\n") || printf " ... not removed (probably not empty)\n"
cd ..
printf "Removing top-level installation directory: \"/usr/local/\""
(rmdir "/usr/local/" 2>/dev/null && printf "\n") || printf " ... not removed (probably not empty)\n"

# Return to the directory from which the program was called
cd ${save_pwd}
